### ISSUE TITLE
Cannot run selenium renderer in docker container

### ISSUE THREAD

**Issue by lancespeelmon** [lancespeelmon/image_crawler#6]
```
make docker-run

Traceback (most recent call last):
  File "./sync_crawler.py", line 37, in <module>
    main()
  File "./sync_crawler.py", line 30, in main
    worker(unit)
  File "./sync_crawler.py", line 24, in worker
    raise ex
  File "./sync_crawler.py", line 16, in worker
    (files_downloaded, exceptions) = crawler.crawl(
  File "/app/crawler/html_crawler.py", line 113, in crawl
    content = self.get_content(url, render)
  File "/app/crawler/html_crawler.py", line 99, in get_content
    self.init_selenium()
  File "/app/crawler/html_crawler.py", line 43, in init_selenium
    self._driver = webdriver.Chrome(options=driver_options)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by lancespeelmon** [comment]
```
RUN apt-get update && apt-get install -y --no-install-recommends chromium-driver
```
